// Keep in sync with the notification detail builder; verified by webhook-facts.test.ts.
export const WEBHOOK_FACT_LABELS: Record<string, string> = {
  credential_name: "credentialName",
  linked_totp: "linkedTotp",
  session_comment: "sessionComment",
  login_ip: "loginIp",
  ip_location: "ipLocation",
  auth_method: "authMethod",
  login_provider: "loginProvider",
  grant_type: "grantType",
  remember_login: "rememberLogin",
  session_expires_at: "sessionExpiresAt",
  session_id: "sessionId",
  logout_source: "logoutSource",
  login_time: "loginTime",
  source_ip: "sourceIp",
  failure_attempts: "failureAttempts",
  retry_wait: "retryWait",
  limit_until: "limitUntil",
  original_ip: "originalIp",
  original_location: "originalLocation",
  current_ip: "currentIp",
  current_location: "currentLocation",
  drift_source: "driftSource",
  hit_count: "hitCount",
  observation_window: "observationWindow",
  trigger_threshold: "triggerThreshold",
  blocked_at: "blockedAt",
  recent_paths: "recentPaths",
  target: "target",
  provider: "provider",
  target_type: "targetType",
  trigger: "trigger",
  update_scope: "updateScope",
  ip_source: "ipSource",
  ipv4_change: "ipv4Change",
  ipv6_change: "ipv6Change",
  result: "result",
  block_duration: "blockDuration",
  blocked_until: "blockedUntil",
  rate_limit: "rateLimit",
  burst_capacity: "burstCapacity",
  target_host: "targetHost",
  request_path: "requestPath",
  route_type: "routeType",
  auth_route: "authRoute",
  request_method: "requestMethod",
  request_scheme: "requestScheme",
  route_key: "routeKey",
  visibility_scope: "visibilityScope",
  visibility_mode: "visibilityMode",
  status_code: "statusCode",
  request_address: "requestAddress",
  outcome: "outcome",
  waf_action: "wafAction",
  waf_mode: "wafMode",
  rule_ids: "ruleIds",
  rule_bundle: "ruleBundle",
  user: "user",
  port: "port",
  log_time: "logTime",
  invalid_user: "invalidUser",
  threshold: "threshold",
  window: "window",
  blocked_reason: "blockedReason",
  related_user: "relatedUser",
  current_version: "currentVersion",
  latest_version: "latestVersion",
  check_reason: "checkReason",
  force_update: "forceUpdate",
  release_notes: "releaseNotes",
  hostname: "hostname",
  current_usage: "currentUsage",
  alert_threshold: "alertThreshold",
  recover_threshold: "recoverThreshold",
  sample_interval: "sampleInterval",
  sustain_duration: "sustainDuration",
  tunnel_type: "tunnelType",
  connection_status: "connectionStatus",
  process_pid: "processPid",
  runtime_feedback: "runtimeFeedback",
  terminal_action: "terminalAction",
  terminal_target: "terminalTarget",
  terminal_session: "terminalSession",
  terminal_revision: "terminalRevision",
  error_code: "errorCode",
  event_type: "eventType",
  risk_level: "riskLevel",
  event_source: "eventSource",
  happened_at: "happenedAt",
  aggregation_stats: "aggregationStats",
  host: "host",
};

export const WEBHOOK_COMMON_FACTS = [
  "event_type",
  "risk_level",
  "event_source",
  "happened_at",
  "aggregation_stats",
];

export const WEBHOOK_EVENT_FACTS = [
  {
    event: "FN_EVENT_AUTH_LOGIN_SUCCESS",
    keys: [
      "credential_name",
      "linked_totp",
      "session_comment",
      "login_ip",
      "ip_location",
      "auth_method",
      "login_provider",
      "grant_type",
      "remember_login",
      "session_expires_at",
      "session_id",
    ],
  },
  {
    event: "FN_EVENT_AUTH_LOGOUT",
    keys: [
      "credential_name",
      "linked_totp",
      "session_comment",
      "login_ip",
      "ip_location",
      "logout_source",
      "login_time",
      "session_id",
    ],
  },
  {
    event: "FN_EVENT_AUTH_LOGIN_FAILURE",
    keys: [
      "source_ip",
      "ip_location",
      "failure_attempts",
      "auth_method",
      "credential_name",
      "linked_totp",
      "retry_wait",
      "limit_until",
    ],
  },
  {
    event: "FN_EVENT_AUTH_SESSION_IP_DRIFT",
    keys: [
      "credential_name",
      "linked_totp",
      "session_comment",
      "auth_method",
      "original_ip",
      "original_location",
      "current_ip",
      "current_location",
      "drift_source",
      "login_time",
      "session_id",
    ],
  },
  {
    event: "FN_EVENT_SECURITY_SCANNER_BLOCKED",
    keys: [
      "source_ip",
      "ip_location",
      "hit_count",
      "observation_window",
      "trigger_threshold",
      "blocked_at",
      "recent_paths",
    ],
  },
  {
    event: "FN_EVENT_DDNS_UPDATE_COMPLETED",
    keys: [
      "target",
      "provider",
      "target_type",
      "trigger",
      "update_scope",
      "ip_source",
      "ipv4_change",
      "ipv6_change",
      "result",
    ],
  },
  {
    event: "FN_EVENT_GATEWAY_THROTTLE_BLOCKED",
    keys: [
      "source_ip",
      "ip_location",
      "block_duration",
      "blocked_until",
      "rate_limit",
      "burst_capacity",
      "target_host",
      "request_path",
      "route_type",
      "auth_route",
    ],
  },
  {
    event: "FN_EVENT_GATEWAY_VISIBILITY_BLOCKED",
    keys: [
      "source_ip",
      "ip_location",
      "blocked_at",
      "request_method",
      "request_scheme",
      "host",
      "request_path",
      "route_type",
      "route_key",
      "visibility_scope",
      "visibility_mode",
      "status_code",
    ],
  },
  {
    event: "FN_EVENT_WAF_BLOCKED",
    keys: [
      "source_ip",
      "ip_location",
      "host",
      "request_address",
      "outcome",
      "waf_action",
      "waf_mode",
      "rule_ids",
      "rule_bundle",
      "status_code",
      "blocked_at",
    ],
  },
  {
    event: "FN_EVENT_SSH_LOGIN_SUCCESS",
    keys: [
      "user",
      "source_ip",
      "ip_location",
      "auth_method",
      "port",
      "log_time",
    ],
  },
  {
    event: "FN_EVENT_SSH_LOGIN_FAILURE",
    keys: [
      "user",
      "invalid_user",
      "source_ip",
      "ip_location",
      "auth_method",
      "port",
      "failure_attempts",
      "threshold",
      "window",
    ],
  },
  {
    event: "FN_EVENT_SSH_IP_BLOCKED",
    keys: [
      "source_ip",
      "ip_location",
      "blocked_reason",
      "related_user",
      "failure_attempts",
      "window",
      "threshold",
      "blocked_at",
      "blocked_until",
    ],
  },
  {
    event: "FN_EVENT_SYSTEM_APP_UPDATE_AVAILABLE",
    keys: [
      "current_version",
      "latest_version",
      "check_reason",
      "force_update",
      "release_notes",
    ],
  },
  {
    event: "FN_EVENT_SYSTEM_CPU_ALERT",
    keys: [
      "hostname",
      "current_usage",
      "alert_threshold",
      "recover_threshold",
      "sample_interval",
      "sustain_duration",
    ],
  },
  {
    event: "FN_EVENT_SYSTEM_CPU_RECOVERED",
    keys: [
      "hostname",
      "current_usage",
      "alert_threshold",
      "recover_threshold",
      "sample_interval",
      "sustain_duration",
    ],
  },
  {
    event: "FN_EVENT_SYSTEM_MEMORY_ALERT",
    keys: [
      "hostname",
      "current_usage",
      "alert_threshold",
      "recover_threshold",
      "sample_interval",
      "sustain_duration",
    ],
  },
  {
    event: "FN_EVENT_SYSTEM_MEMORY_RECOVERED",
    keys: [
      "hostname",
      "current_usage",
      "alert_threshold",
      "recover_threshold",
      "sample_interval",
      "sustain_duration",
    ],
  },
  {
    event: "FN_EVENT_TUNNEL_FRP_CONNECTED",
    keys: [
      "tunnel_type",
      "connection_status",
      "process_pid",
      "runtime_feedback",
    ],
  },
  {
    event: "FN_EVENT_TUNNEL_FRP_DISCONNECTED",
    keys: [
      "tunnel_type",
      "connection_status",
      "process_pid",
      "runtime_feedback",
    ],
  },
  {
    event: "FN_EVENT_TUNNEL_CLOUDFLARED_CONNECTED",
    keys: [
      "tunnel_type",
      "connection_status",
      "process_pid",
      "runtime_feedback",
    ],
  },
  {
    event: "FN_EVENT_TUNNEL_CLOUDFLARED_DISCONNECTED",
    keys: [
      "tunnel_type",
      "connection_status",
      "process_pid",
      "runtime_feedback",
    ],
  },
  {
    event: "FN_EVENT_TERMINAL_AUDIT",
    keys: [
      "terminal_action",
      "terminal_target",
      "terminal_session",
      "terminal_revision",
      "error_code",
    ],
  },
];
