import { tryOnScopeDispose } from "@vueuse/core";
import { ref, watch, type Ref } from "vue";

export interface DragScrollOptions {
  /**
   * Minimum horizontal pointer travel (in pixels) before a gesture is treated
   * as a drag. Movements below this threshold are treated as a plain click so
   * links and buttons inside the scrollable region keep working.
   */
  dragThreshold?: number;
}

/**
 * Enables horizontal drag-to-scroll for a scrollable element using a mouse
 * ("grab" hand cursor). Touch devices keep their native `overflow-x-auto`
 * panning, so only mouse gestures are intercepted here.
 *
 * Pointer move/end are tracked on `window` (not the element) so the drag always
 * ends cleanly even when the cursor leaves the element or the window loses
 * focus mid-drag.
 */
export const useDragScroll = (
  elementRef: Ref<HTMLElement | null>,
  { dragThreshold = 6 }: DragScrollOptions = {},
) => {
  const isDragging = ref(false);

  let activePointerId: number | null = null;
  let startClientX = 0;
  let startScrollLeft = 0;
  let dragged = false;
  let resetDraggedTimer: ReturnType<typeof setTimeout> | null = null;

  const clearDraggedReset = () => {
    if (resetDraggedTimer === null) return;
    clearTimeout(resetDraggedTimer);
    resetDraggedTimer = null;
  };

  const resetDraggedAfterClick = () => {
    clearDraggedReset();
    // A click generated by this pointer gesture is dispatched immediately
    // after pointerup. Do not let a drag with no resulting click suppress a
    // later, unrelated click.
    resetDraggedTimer = setTimeout(() => {
      dragged = false;
      resetDraggedTimer = null;
    }, 0);
  };

  const removeGlobalListeners = () => {
    window.removeEventListener("pointermove", handleGlobalPointerMove);
    window.removeEventListener("pointerup", handleGlobalPointerUp);
    window.removeEventListener("pointercancel", handleGlobalPointerUp);
    window.removeEventListener("blur", handleWindowBlur);
  };

  const handleGlobalPointerMove = (event: PointerEvent) => {
    if (activePointerId === null || event.pointerId !== activePointerId) return;
    const el = elementRef.value;
    if (!el) return;

    const deltaX = event.clientX - startClientX;
    if (!dragged && Math.abs(deltaX) >= dragThreshold) {
      dragged = true;
      isDragging.value = true;
    }
    if (dragged) {
      event.preventDefault();
      el.scrollLeft = startScrollLeft - deltaX;
    }
  };

  const endDrag = () => {
    if (activePointerId === null) return;
    activePointerId = null;
    isDragging.value = false;
    removeGlobalListeners();
  };

  const handleGlobalPointerUp = (event: PointerEvent) => {
    if (activePointerId === null || event.pointerId !== activePointerId) return;
    const shouldSuppressClick = dragged && event.type === "pointerup";
    endDrag();
    if (shouldSuppressClick) resetDraggedAfterClick();
    else dragged = false;
  };

  const handleWindowBlur = () => {
    if (activePointerId !== null) endDrag();
    dragged = false;
    clearDraggedReset();
  };

  const addGlobalListeners = () => {
    window.addEventListener("pointermove", handleGlobalPointerMove);
    window.addEventListener("pointerup", handleGlobalPointerUp);
    window.addEventListener("pointercancel", handleGlobalPointerUp);
    window.addEventListener("blur", handleWindowBlur);
  };

  const onPointerDown = (event: PointerEvent) => {
    const el = elementRef.value;
    if (!el || event.button !== 0 || event.pointerType !== "mouse") return;

    // Some Android/Huawei WebViews have reported touch-originated pointer
    // events as `mouse`. Only enable mouse drag scrolling when the environment
    // also exposes a fine, hover-capable primary pointer, and reject events
    // that still carry touch source/contact information. Otherwise a small
    // finger movement can suppress the first click and make every item appear
    // to require a second tap.
    const pointerQuery = window.matchMedia?.(
      "(hover: hover) and (pointer: fine)",
    );
    if (pointerQuery && !pointerQuery.matches) return;
    const sourceCapabilities = (
      event as PointerEvent & {
        sourceCapabilities?: { firesTouchEvents?: boolean } | null;
      }
    ).sourceCapabilities;
    if (sourceCapabilities?.firesTouchEvents === true) return;
    if ((event.width ?? 1) > 1 || (event.height ?? 1) > 1) return;

    // Nothing to drag when the content already fits within the viewport.
    if (el.scrollWidth <= el.clientWidth) return;

    activePointerId = event.pointerId;
    startClientX = event.clientX;
    startScrollLeft = el.scrollLeft;
    dragged = false;
    isDragging.value = false;
    clearDraggedReset();

    // Keep pointerdown untouched so links inside the scrolling region retain
    // their native click behavior. Global listeners are enough to finish a
    // drag even if the pointer leaves the element.
    addGlobalListeners();
  };

  /**
   * Fires in the capture phase, before the click reaches any child link. After
   * a real drag the synthetic click must not open the dragged link.
   */
  const handleClickCapture = (event: MouseEvent) => {
    if (!dragged) return;
    event.preventDefault();
    event.stopPropagation();
    dragged = false;
    clearDraggedReset();
  };

  // Register the click guard with addEventListener so the element's template
  // stays free of a click handler on a non-interactive element.
  const stopClickGuard = watch(
    elementRef,
    (el, previous) => {
      previous?.removeEventListener("click", handleClickCapture, true);
      el?.addEventListener("click", handleClickCapture, true);
    },
    { immediate: true },
  );

  tryOnScopeDispose(() => {
    stopClickGuard();
    removeGlobalListeners();
    clearDraggedReset();
    const el = elementRef.value;
    el?.removeEventListener("click", handleClickCapture, true);
    activePointerId = null;
    isDragging.value = false;
  });

  return {
    isDragging,
    onPointerDown,
  };
};
