export const AUTH_DECISION_LABEL_KEYS: Readonly<Record<string, string>> = {
  passed: "admin.gatewayRequestLogs.authDecisions.passed",
  redirected: "admin.gatewayRequestLogs.authDecisions.redirected",
  denied: "admin.gatewayRequestLogs.authDecisions.denied",
  access_denied: "admin.gatewayRequestLogs.authDecisions.accessDenied",
  root_mode_redirect: "admin.gatewayRequestLogs.authDecisions.rootModeRedirect",
  not_required: "admin.gatewayRequestLogs.authDecisions.notRequired",
  proxy: "admin.gatewayRequestLogs.authDecisions.proxy",
  error: "admin.gatewayRequestLogs.authDecisions.error",
  general_blacklist_blocked:
    "admin.gatewayRequestLogs.authDecisions.generalBlacklistBlocked",
  connection_reset: "admin.gatewayRequestLogs.authDecisions.connectionReset",
  subdomain_rule_allowed:
    "admin.gatewayRequestLogs.authDecisions.subdomainRuleAllowed",
  waf_blocked: "admin.gatewayRequestLogs.authDecisions.wafBlocked",
  robots_txt_served: "admin.gatewayRequestLogs.authDecisions.robotsTxtServed",
  crawler_blocked: "admin.gatewayRequestLogs.authDecisions.crawlerBlocked",
  visibility_denied: "admin.gatewayRequestLogs.authDecisions.visibilityDenied",
  fn_app_prompt: "admin.gatewayRequestLogs.authDecisions.fnAppPrompt",
  rate_limited: "admin.gatewayRequestLogs.authDecisions.rateLimited",
  bypassed: "admin.gatewayRequestLogs.authDecisions.bypassed",
  public: "admin.gatewayRequestLogs.authDecisions.public",
  rule_missing: "admin.gatewayRequestLogs.authDecisions.ruleMissing",
  binding_token: "admin.gatewayRequestLogs.authDecisions.bindingToken",
  scope_denied: "admin.gatewayRequestLogs.authDecisions.scopeDenied",
  http1_required: "admin.gatewayRequestLogs.authDecisions.http1Required",
  http2_required: "admin.gatewayRequestLogs.authDecisions.http2Required",
  disabled: "admin.gatewayRequestLogs.authDecisions.disabled",
  outside_window: "admin.gatewayRequestLogs.authDecisions.outsideWindow",
  schedule_closed: "admin.gatewayRequestLogs.authDecisions.scheduleClosed",
  advanced_bypass: "admin.gatewayRequestLogs.authDecisions.advancedBypass",
  auth_unconfigured: "admin.gatewayRequestLogs.authDecisions.authUnconfigured",
  auth_error: "admin.gatewayRequestLogs.authDecisions.authError",
  timeout: "admin.gatewayRequestLogs.authDecisions.timeout",
  queue_full: "admin.gatewayRequestLogs.authDecisions.queueFull",
  disconnected: "admin.gatewayRequestLogs.authDecisions.disconnected",
  bridge_unavailable:
    "admin.gatewayRequestLogs.authDecisions.bridgeUnavailable",
  invalid_response: "admin.gatewayRequestLogs.authDecisions.invalidResponse",
  internal: "admin.gatewayRequestLogs.authDecisions.internal",
};
