<script setup lang="ts">
import ScanDiscoveryIntensityDialog from "@/components/ScanDiscoveryIntensityDialog.vue";
import { docsUrls } from "../../lib/docs";
import SubdomainMappingsCard from "./SubdomainMappingsCard.vue";
import SubdomainModeConfigCard from "./SubdomainModeConfigCard.vue";
import type { SubdomainProxyOverviewController } from "./useSubdomainProxyPage";

const props = defineProps<{ controller: SubdomainProxyOverviewController }>();
const {
  activeDeepMonitorHosts,
  activeEdgeClientIpProvider,
  addAuthService,
  allMappings,
  authServiceMapping,
  authServicePublicPort,
  canManageNewMappings,
  clearDefaultMapping,
  configStore,
  copyMappingHost,
  discoverButtonDividerClass,
  discoverButtonVariant,
  draggableVisibleMappings,
  edgeClientIpProviderOptions,
  exportBookmarks,
  filteredMappings,
  formatAuthServiceHostWithPublicPort,
  formatAvailabilityWindow,
  formatHostWithAccessEntryPort,
  getAvailabilityState,
  getHostTrafficSample,
  getMappingTitleForDisplay,
  globalVisibilityEnabled,
  globalWafEnabled,
  handleMappingStatusTooltipOpenChange,
  handleMappingStatusTooltipTriggerClick,
  handleProtocolHeadersWarningOpenChange,
  hasRegularHostMappings,
  hostMappingGroupedView,
  hostMappingGroups,
  isAuthServiceTarget,
  isClearingAllSubdomainConfig,
  isDefaultDomainAvailable,
  isDiscovering,
  isEdgeClientIPModeEditable,
  isExportingBookmarks,
  isFaviconBroken,
  isGatewayPortalEnabled,
  isMappingStatusTooltipOpen,
  isMappingUnavailable,
  isModeDirty,
  isModeValid,
  isProtocolHeadersWarningOpen,
  isRefreshingTitles,
  isRootDomainPendingSave,
  isSavingMappings,
  isSavingMode,
  isScanIntensityDialogOpen,
  isSubdomainModeConfigured,
  isSyncing,
  markFaviconBroken,
  modeForm,
  moveMappingsToGroup,
  omitPublicPortConfiguration,
  openAdvancedAuth,
  openBatchAvailability,
  openBatchMutation,
  openAvailabilityDialog,
  openClearAllConfigDialog,
  openCreateDialog,
  openDeepMonitor,
  openDeleteMappingDialog,
  openDiscoverDialog,
  openEditDialog,
  openGatewayLocations,
  openProtocolHeadersWarning,
  openStaleCleanupDialog,
  openTargetOptimization,
  openToggleMappingDialog,
  refreshAllTitles,
  removeAuthService,
  resetModeForm,
  rootDomainValidationMessage,
  saveGroupedMappingOrder,
  saveMappingGroups,
  saveMappingOrder,
  saveMode,
  savedEdgeClientIpProviderLabel,
  savedRootDomain,
  scheduleCloseProtocolHeadersWarning,
  searchQuery,
  selectEdgeClientIpProvider,
  setDefaultMapping,
  shouldShowProtocolHeadersWarning,
  syncRoutes,
  toggleProtocolHeadersWarning,
  trafficRealtimeStats,
  updateHostMappingGroupedView,
  visibleMappings,
} = props.controller;
</script>

<template>
  <div class="space-y-6">
    <SubdomainModeConfigCard
        v-model:auth-service-public-port="authServicePublicPort"
        v-model:edge-client-ip-enabled="modeForm.edge_client_ip_enabled"
        v-model:root-domain="modeForm.root_domain"
        :active-edge-client-ip-provider="activeEdgeClientIpProvider"
        :auth-service-mapping="authServiceMapping"
        :configured="isSubdomainModeConfigured"
        :ready="!configStore.isLoading"
        :edge-client-ip-provider-options="edgeClientIpProviderOptions"
        :format-auth-service-host="formatAuthServiceHostWithPublicPort"
        :is-edge-client-ip-mode-editable="isEdgeClientIPModeEditable"
        :is-mode-dirty="isModeDirty"
        :is-mode-valid="isModeValid"
        :is-saving-mappings="isSavingMappings"
        :is-saving-mode="isSavingMode"
        :omit-public-port-configuration="omitPublicPortConfiguration"
        :remove-auth-service="removeAuthService"
        :reset-mode-form="resetModeForm"
        :root-domain-validation-message="rootDomainValidationMessage"
        :save-mode="saveMode"
        :saved-edge-client-ip-provider-label="savedEdgeClientIpProviderLabel"
        :saved-root-domain="savedRootDomain"
        :select-edge-client-ip-provider="selectEdgeClientIpProvider"
    />
    <SubdomainMappingsCard
        v-model:draggable-mappings="draggableVisibleMappings"
        v-model:search-query="searchQuery"
        :all-mappings-count="allMappings.length"
        :all-regular-mappings="visibleMappings"
        :auth-service-mapping="authServiceMapping"
        :can-manage-new-mappings="canManageNewMappings"
        :active-deep-monitor-hosts="activeDeepMonitorHosts"
        :can-use-deep-monitor="configStore.canUseDeepMonitor"
        :discover-button-divider-class="discoverButtonDividerClass"
        :discover-button-variant="discoverButtonVariant"
        :docs-href="docsUrls.guides.subdomainProxy"
        :filtered-mappings="filteredMappings"
        :format-availability-window="formatAvailabilityWindow"
        :format-host="formatHostWithAccessEntryPort"
        :get-availability-state="getAvailabilityState"
        :get-host-traffic-sample="getHostTrafficSample"
        :get-mapping-title-for-display="getMappingTitleForDisplay"
        :global-visibility-enabled="globalVisibilityEnabled"
        :global-waf-enabled="globalWafEnabled"
        :grouped-view="hostMappingGroupedView"
        :groups="hostMappingGroups"
        :handle-mapping-status-tooltip-open-change="
          handleMappingStatusTooltipOpenChange
        "
        :handle-mapping-status-tooltip-trigger-click="
          handleMappingStatusTooltipTriggerClick
        "
        :handle-protocol-headers-warning-open-change="
          handleProtocolHeadersWarningOpenChange
        "
        :has-regular-host-mappings="hasRegularHostMappings"
        :is-auth-service-target="isAuthServiceTarget"
        :is-clearing-all-subdomain-config="isClearingAllSubdomainConfig"
        :is-config-loading="configStore.isLoading"
        :is-discovering="isDiscovering"
        :is-exporting-bookmarks="isExportingBookmarks"
        :is-favicon-broken="isFaviconBroken"
        :is-gateway-portal-enabled="isGatewayPortalEnabled"
        :is-default-domain-available="isDefaultDomainAvailable"
        :is-mapping-unavailable="isMappingUnavailable"
        :is-mapping-status-tooltip-open="isMappingStatusTooltipOpen"
        :is-protocol-headers-warning-open="isProtocolHeadersWarningOpen"
        :is-refreshing-titles="isRefreshingTitles"
        :is-root-domain-pending-save="isRootDomainPendingSave"
        :is-saving-mappings="isSavingMappings"
        :is-syncing="isSyncing"
        :mark-favicon-broken="markFaviconBroken"
        :open-protocol-headers-warning="openProtocolHeadersWarning"
        :root-domain-validation-message="rootDomainValidationMessage"
        :saved-root-domain="savedRootDomain"
        :schedule-close-protocol-headers-warning="
          scheduleCloseProtocolHeadersWarning
        "
        :should-show-protocol-headers-warning="shouldShowProtocolHeadersWarning"
        :toggle-protocol-headers-warning="toggleProtocolHeadersWarning"
        :traffic-timestamp="trafficRealtimeStats?.timestamp ?? null"
        :visible-mappings-count="visibleMappings.length"
        @add-auth-service="addAuthService"
        @batch-delete="
          (hosts, onComplete) => openBatchMutation(hosts, 'delete', onComplete)
        "
        @batch-disable="
          (hosts, onComplete) => openBatchMutation(hosts, 'disable', onComplete)
        "
        @batch-enable="
          (hosts, onComplete) => openBatchMutation(hosts, 'enable', onComplete)
        "
        @batch-schedule="openBatchAvailability"
        @clear-default="clearDefaultMapping"
        @copy-host="copyMappingHost"
        @delete="openDeleteMappingDialog"
        @edit="openEditDialog"
        @export-bookmarks="exportBookmarks"
        @move-mappings="
          async (hosts, groupId, onComplete) => {
            if (await moveMappingsToGroup(hosts, groupId)) onComplete?.();
          }
        "
        @open-clear-all-config="openClearAllConfigDialog"
        @open-create="openCreateDialog"
        @open-discover="openDiscoverDialog"
        @open-discover-settings="isScanIntensityDialogOpen = true"
        @open-availability="openAvailabilityDialog"
        @open-gateway-locations="openGatewayLocations"
        @open-advanced-auth="openAdvancedAuth"
        @open-deep-monitor="openDeepMonitor"
        @open-stale-cleanup="openStaleCleanupDialog"
        @open-target-optimization="openTargetOptimization"
        @refresh-all-titles="refreshAllTitles"
        @save-order="saveMappingOrder"
        @save-grouped-order="saveGroupedMappingOrder"
        @save-groups="saveMappingGroups"
        @set-default="setDefaultMapping"
        @sync-routes="syncRoutes"
        @toggle-enabled="openToggleMappingDialog"
        @update-grouped-view="updateHostMappingGroupedView"
    />

    <ScanDiscoveryIntensityDialog
      v-model:open="isScanIntensityDialogOpen"
      :disabled="isDiscovering"
    />
  </div>
</template>
