const BACKUP_EXCLUDED_KEY_PREFIXES = [
  "fn_knock:acme:job:",
  "fn_knock:acme:logs:",
  "fn_knock:auth_log_data:",
  "fn_knock:auth_logs:",
  "fn_knock:auth_mobility:",
  "fn_knock:backoff:",
  "fn_knock:cidr:",
  "fn_knock:cloudflared:logs",
  "fn_knock:common_auth_locations:runtime",
  "fn_knock:config:backup:",
  "fn_knock:docker_admin:login_backoff:",
  "fn_knock:docker_admin:session:",
  "fn_knock:errors:",
  "fn_knock:events:",
  "fn_knock:fnos-share:session:",
  "fn_knock:fnos-share:validation:",
  "fn_knock:gateway:",
  "fn_knock:ip_location:",
  "fn_knock:lock:",
  "fn_knock:login_backoff:",
  "fn_knock:nonce:",
  "fn_knock:notifications:deliveries:",
  "fn_knock:notifications:runtime:",
  "fn_knock:notifications:triggers:",
  "fn_knock:oidc:invite:",
  "fn_knock:oidc:login_error:",
  "fn_knock:oidc:state:",
  "fn_knock:passkey:bind:",
  "fn_knock:passkey:challenge:",
  "fn_knock:recent_auth_ips:",
  "fn_knock:reverse-proxy:",
  "fn_knock:scanner:blacklist:",
  "fn_knock:scanner:suspicious:",
  "fn_knock:session:",
  "fn_knock:smart-connect:runtime",
  "fn_knock:ssh_security:",
  "fn_knock:terminal:",
  "fn_knock:traffic:",
  "fn_knock:tunnel:runtime",
  "fn_knock:ui:",
  "fn_knock:update:",
  "fn_knock:waf:log:",
  "fn_knock:waf:logs:",
  "fn_knock:waf:stats:",
  "fn_knock:welcome-guide:",
] as const;

const BACKUP_EXCLUDED_KEY_PATTERNS = [
  /^fn_knock:acme:runtime-lock$/,
  /^fn_knock:ddns:last_(?:ip|check)$/,
  /^fn_knock:ddns:logs(?::seq)?$/,
  /^fn_knock:ddns:v2:target:[^:]+:last_(?:ip|check)$/,
  /^fn_knock:frpc:v2:instance:[^:]+:(?:runtime|logs(?::seq)?)$/,
] as const;

export const shouldExportBackupKey = (key: string): boolean =>
  !BACKUP_EXCLUDED_KEY_PREFIXES.some((prefix) => key.startsWith(prefix)) &&
  !BACKUP_EXCLUDED_KEY_PATTERNS.some((pattern) => pattern.test(key));
