#!/bin/sh
set -e

[ -n "$IPKG_INSTROOT" ] && exit 0

if [ -x /etc/init.d/fn-knock ]; then
	/etc/init.d/fn-knock stop >/dev/null 2>&1 || true
	/etc/init.d/fn-knock disable >/dev/null 2>&1 || true
fi

if [ -x /var/lib/fn-knock/clean.sh ]; then
	/var/lib/fn-knock/clean.sh >/dev/null 2>&1 || true
fi

exit 0
